#!/bin/bash

# Short and simple Bash Script to start the preview

echo "SysP2020-21 Codeleser"
echo ""
cd /home/pi/Projekte/SysP2020_21_Codeleser
echo -e "Working on:\n"
git show -s --format=medium --abbrev-commit
echo ""
python3 preview.py