#!/bin/bash

# Short and simple Bash Script to capture image

echo "SysP2020-21 Codeleser"
echo "Launching program to capture image"
echo ""

cd /home/pi/Projekte/SysP2020_21_Codeleser
echo -e "Working on:\n"
git show -s --format=medium --abbrev-commit
echo ""
python3 raspi/image_info.py

exec $SHELL